# Generated by Django 5.2.6 on 2025-10-10 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotina',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rotinas.categoria'),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
