# Generated by Django 5.2.6 on 2025-11-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotinas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='pictograma_padrao',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='pictograma_upload',
        ),
        migrations.AddField(
            model_name='rotina',
            name='pictograma_padrao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rotina',
            name='pictograma_upload',
            field=models.ImageField(blank=True, null=True, upload_to='pictogramas_rotina/'),
        ),
    ]
