# Generated by Django 5.2.6 on 2025-11-04 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotinas', '0003_categoria_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterModelOptions(
            name='rotina',
            options={},
        ),
        migrations.RemoveField(
            model_name='rotina',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='rotina',
            name='pictograma',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='pictograma',
            field=models.ImageField(blank=True, null=True, upload_to='pictogramas_atividades/'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('nome', 'usuario'), name='unique_categoria_por_usuario'),
        ),
    ]
