# Generated by Django 5.2.6 on 2025-11-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotinas', '0005_alter_categoria_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='pictograma_padrao',
            field=models.ImageField(blank=True, null=True, upload_to='pictogramas_categoria/'),
        ),
    ]
